### ISSUE TITLE
Couldn't find preset "es2015" on relative directory 'node_modules/immutable-datetime'

### ISSUE THREAD

**Issue by theredfoxfire** [kodefox/immutable-datetime#1]
I am try to implement this package in react-native IoS. Then those error is blooming.

**Comment by sstur** [comment]
Oops, I think maybe I missed a dependency.

**Comment by sstur** [comment]
Thanks @theredfoxfire. The issue was because I didn't `npmignore` my eslintrc file. This is fixed in v0.2.2
